### ISSUE TITLE
EuroVis 2023 Poster Plan

### ISSUE THREAD

**Issue by yilinxia** [cropsinsilico/jupyterlab_nodeeditor#24]
In this poster, we are trying to compare the traditional method (tradition) and the one we created (jlne) in schema matching

The function we need to implement for the poster
- [source schema transformation] interlocked components for the data which we are not able to digest directly through a function from yt
- [target schema transformation] based on the required parameters of a python function, we generate another group of components
- [json file generation] after users interlock the two groups of interlocked components, then we can generate a json file

If time permit (content for papers)
- [dataset test] we need some typical formats of dataset from astromy 
    - to test the function of the tool 
    - to justify the impacts of the tool
- [recommended components] when selecting certain components included in the yt function, the source schema part will highlight the potentail matchable components to speed up the matching process
- [user study] hire maybe 12 participants (maybe from the yt community) to use these two methods to do some work and evaluate their feedback
   -  time needed to complete the matching task
   - cognitive load to use the two tools

challenges in my mind
- will the tool be applicable to dataset with complex schemas?
- how this tool differ from previous tools in general? (need papers to support this opinion)

**Comment by matthewturk** [comment]
Hi @yilinxia , I know I said to make the issue here, but upon reading it I think this is not really related to this project as much as it is to others.  I will talk with you offline about how and why this work should be directed specifically to the crops in silico project, which doesn't really match the outline here.
